### ISSUE TITLE
Feature request: Fix audio control console on C152

### ISSUE THREAD

**Issue by adempewolff** [DRF30q/C152X#1]
Seems like a great mod, I'm looking forward to trying it out.

Any plans to fix the issues with switches/functionality of the audio control console?  As far as I can tell, there is no way to monitor the ADF receiver.

It appears to be modeled after the Bendix [KA-134](https://salt.aero/wp-content/uploads/2016/04/BENDIX-KA134-Pilots-Guide.pdf) audio control console.  However, the "ADF" button is mislabeled "AOF" and is inoperable.  The DME button is operable (which is strange because I don't see any indicators that it has a DME transmitter/receiver) but does nothing.

**Comment by erikgeo** [comment]
Also, pushing the nav1/2 to get the morse code identifier will cause the morse code to sound indefinitely. No way to turn it off other than cutting the volume. Or is that realistic? I suppose not...

**Comment by DRF30q** [comment]
Audio panel now update with V0.16.
