### ISSUE TITLE
Radios "don't turn on"

### ISSUE THREAD

**Issue by Flyingscool** [DRF30q/C152X#11]
Actually, they do, but it looks like they're not because the text doesn't light up (the swap buttons do though).  Turns out when you redid the electrical layout, you disabled the XML file which is somehow related to bus 2.  That XML used to be entry 34.
Now the Taxi Lights switch turns on the text of the radios because now it's entry 34.

To fix the problem, I changed the reference from 34 to 2 in the xml file, and now the radios' text turns on appropriately.
I'm not sure I like this fix, because if people create their own custom panels, then they'll be confused why the radios don't turn on.  We could fix this by making GENERAL_PANEL entry 34, but I don't know if MSFS would like that, or what other issues that might introduce if they've done any linking back to this file like they did for the panel.xml file.

Anyway, here's how I fixed the problem.  Maybe you'll have a better idea..

`<PlaneHTMLConfig>

	<Instrument>
		<Name>C300ADF</Name>
		<Electric>
			<And>
				<Greater>
					<Simvar name="ADF VOLUME:1" unit="Percent"/>
					<Constant>0</Constant>
				</Greater>
				<Simvar name="CIRCUIT ON:2" unit="Boolean"/>
			</And>
		</Electric>
	</Instrument>
	<Instrument>
		<Name>KX155A_1</Name>
		<Electric>
			<Simvar name="CIRCUIT ON:2" unit="Boolean"/>
		</Electric>
	</Instrument>
	<Instrument>
		<Name>KX155A_2</Name>
		<Electric>
			<Simvar name="CIRCUIT ON:2" unit="Boolean"/>
		</Electric>
	</Instrument>
	<Instrument>
		<Name>HourMeter</Name>
		<Electric>
			<Simvar name="CIRCUIT ON:2" unit="Boolean"/>
		</Electric>
	</Instrument>

</PlaneHTMLConfig>
  `

**Comment by havber** [comment]
I had this issue with 0.15 (after the latest msfs patch), but just tested 0.16, and it seems to be fine now? You do have to turn the navcom on with the rotary knobs, though, don't think that was the case before. Great work on this mod!

**Comment by Flyingscool** [comment]
Oh, I didn't see .16... did that come out today?

**Comment by Flyingscool** [comment]
Ha!  Yay!  I'll be interested to see how he fixed it :)
I'm just a hack...
