### ISSUE TITLE
ADF malfunction

### ISSUE THREAD

**Issue by daveji** [DRF30q/C152X#21]
C152 has worked fine for days with C152X in use.
Suddenly today the ADF does not work if AC is started cold and dark, ie off runway,.......... if a "Gamer start" is used with  engine running it does work, whether the C152X mod (version 1.7) in use or not.
When faulty tuning knob digit display responds to mousewheel intermittently, and ADF does not tune to frequency...... the needle twitches from "3 to 4 o'clock" not to the beacon.
This issue has happened before starting in any location, , the ADF always has been "flakey" but reinstalling the mod has invariably fixed the problem
Today this workaround has not worked despite several attempts.

**Comment by LavaTiger99** [comment]
I have the same issue

**Comment by daveji** [comment]
The latest version fixes this and works well.
The active page has changed......see github.com/JPLogistics/MSFS_C152/releases/tag/V0.8.3
