### ISSUE TITLE
Aircraft won't start!

### ISSUE THREAD

**Issue by Meowsaviation** [DRF30q/C152X#7]
Aircraft won't ignite.
When I try to start it (switch magneto to START) it will flick back to BOTH and won't start the engine.
Tried everything.
I follow a "real life" C152 checklist. Weird...

**Comment by WallyCZ** [comment]
Keep hold mouse button (or key)on START position for long...

**Comment by philipzangara** [comment]
Did you try opening the fuel valve and setting mixture to full?

**Comment by Meowsaviation** [comment]
> Did you try opening the fuel valve and setting mixture to full?

Yeah

**Comment by Meowsaviation** [comment]
> > Did you try opening the fuel valve and setting mixture to full?
> 
> Yeah

**Comment by vermin01** [comment]
Was happening for me too, Load it cold and dark, fuel control on, mixture rich, prime as needed, throttle cracked, just cranks and cranks and never started. 

I deleted the old folder and loaded version 0.16, it started with a sputter. seems to be working for me now. 
Plane flies great, thank you for all your work!

**Comment by ChrizzyO** [comment]
There is an issue if u try to start it using the Honeycomb yoke´s start switch! It doesnt hold the key in start position.. need to use the mouse to start it! Hope that get´s fixed soon..

**Comment by tgcbraun** [comment]
Same issue for me with the Logitech panel.

**Comment by DRF30q** [comment]
See other issue thread:

"Can't start the engine with the Honeycomb Alpha Flight Controls"
