### ISSUE TITLE
CDI & ADF gauges don't work anymore

### ISSUE THREAD

**Issue by walterbeech** [DRF30q/C152X#8]
Whatever radio aids I tuned work in other aircraft. After these modifications, neither VOR (CDI) nor ADF gauge needles reacted to the beacons. CDIs remained completely frozen, I couldn't even turn the OBS knobs.

**Comment by DRF30q** [comment]
V0.15?  Tried deleting folder completely and reinstalling?

**Comment by walterbeech** [comment]
V0.15, yes. I'm sorry, I haven't yet had time to update this. I tried the deleting-reinstalling and it worked. The problem with the ADF turned out to be the mode selection knob was not defaulted to ADF as I would expect and I just didn't pay attention to it.

**Comment by DRF30q** [comment]
From the next update, the ADF mode knob will default to 'ADF' position.
